name: kids_app_grad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  go_router: ^16.3.0
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.3
  dotted_border: ^2.1.0
  image_picker: ^1.2.1
  http: ^1.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  fl_chart: ^0.71.0 # إضافة مكتبة الرسم البياني

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
